
disk = "./HDD.vdi"
disk_sise_gb = 1

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/hirsute64"

  # upgrade system
  config.vm.provision "shell", inline: <<-SHELL
    export DEBIAN_FRONTEND=noninteractive
    apt-get update && apt-get upgrade -y
    apt-get install apt-transport-https ca-certificates dirmngr

    apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv E0C56BD4
    echo "deb https://repo.clickhouse.tech/deb/stable/ main/" | sudo tee /etc/apt/sources.list.d/clickhouse.list

    apt-get update && apt-get install -y clickhouse-server clickhouse-client
    service clickhouse-server start
  SHELL
end
