HOST_PROJECT = ENV['PROJECT_PATH']
Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"
  config.vm.define "debian11"
  config.vm.hostname = "debian11"
  config.vm.synced_folder HOST_PROJECT, HOST_PROJECT
end
