Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/hirsute64"
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.provider "virtualbox" do |vb|
        vb.cpus = 2
        vb.memory = "4096"
        vb.gui = false
  end
  config.vm.provision "shell", path: "./start-up.sh"
end
