
disk = "./HDD.vdi"
disk_sise_gb = 1

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"


  config.vm.provider "virtualbox" do |vb|
    # create disk
    unless File.exist?(disk)
      vb.customize ['createhd', '--filename', disk, '--variant', 'Fixed', '--size', disk_sise_gb * 1024]
    end
    vb.customize ['storageattach', :id,  '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', disk]
  end

  # upgrade system
  config.vm.provision "shell", inline: <<-SHELL
    export DEBIAN_FRONTEND=noninteractive
    apt-get update && apt-get upgrade -y
  SHELL
end
