Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"

  # upgrade system
  config.vm.provision "shell", inline: <<-SHELL
    export DEBIAN_FRONTEND=noninteractive
    apt-get update && apt-get upgrade -y
  SHELL
end
